branches:
  only:
    - master
sudo: true
language: cpp
os: linux
dist: xenial
compiler:
  - g++
before_install:
  - ./scripts/install-deps
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
