branches:
  only:
    - master
sudo: true
language: cpp
os: linux
dist: xenial
compiler:
  - g++
before_install:
  - sh scripts/install-protobuf.sh
install:
  - sudo apt install libserial-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
